### PR TITLE
Plugin support for field handlers (task #1787)

### PR DESCRIPTION
**Pull request by georgeconstantinou**

### CODE REVIEW

**Comment by mamchenkov** [comment]
@georgeconstantinou maybe it's better to use plugin prefix in the table parameter, if needed, to avoid an extra parameter ... Something like `$table = 'MyFoobarPlugin.Accounts';`.  If that won't work or is too difficult to handle, then we can just merge this implementation.

**Comment by georgeconstantinou** [comment]
@mamchenkov for the related fields in migration files?

**Comment by mamchenkov** [comment]
@georgeconstantinou no, for the field handlers ... like this:

```php
public function renderInput($plugin, $table, $field, $data = '', array $options = [])
```

Instead of adding another parameter `$plugin`, you can still use `$table`.  If you need to specify the table from the plugin, than you can use `PluginName.TableName` notation.

**Comment by georgeconstantinou** [comment]
@mamchenkov got it, will fix.

**Comment by georgeconstantinou** [comment]
@mamchenkov please review

**Comment by flangofas** [comment]
:+1:

**Pull request merged**
